enum SocketError {
  INVALID_PARTY = 'INVALID_PARTY',
  CANNOT_JOIN = 'CANNOT_JOIN',
  MEMBER_EXISTS = 'MEMBER_EXISTS',
  MEMBER_LIMIT = 'MEMBER_LIMIT',
  MESSAGE_FAILED = 'MESSAGE_FAILED',
}

export default SocketError
