version: "3"

services:
  mongo:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME="${DB_USERNAME}"
      - ME_CONFIG_MONGODB_ADMINPASSWORD="${DB_PASSWORD}"
      - ME_CONFIG_MONGODB_URL="mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:${DB_PORT}"
    volumes:
      - "pixeled-mongo:/var/lib/mongo"

volumes:
  pixeled-mongo:
    driver: local
