version: "3"

services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGO_CONNECTION_URL}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    networks:
      - mongo-network

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - "pixeled-mongo:/var/lib/mongo"
    networks:
      - mongo-network

volumes:
  pixeled-mongo:
    driver: local
networks:
  mongo-network:
    external: true
