version: "3"

services:
  mongo:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - MONGO_INITDB_DATABASE=pixelated
    volumes:
      - "pixeled-mongo:/var/lib/mongo"

volumes:
  pixeled-mongo:
    driver: local
