enum SocketError {
  INVALID_PARTY = "INVALID_PARTY",
  CANNOT_JOIN = "CANNOT_JOIN",
  MEMBER_EXISTS = "MEMBER_EXISTS",
  MEMBER_MAX_LIMIT = "MEMBER_MAX_LIMIT",
  MEMBER_MIN_LIMIT = "MEMBER_MIN_LIMIT",
  MESSAGE_FAILED = "MESSAGE_FAILED",
  GAME_FAILED = "GAME_FAILED",
}

export default SocketError;
